### ISSUE TITLE
Load node canvas from memory instead of disk

### ISSUE THREAD

**Issue by richjoslin** [Seneral/Node_Editor#124]
I'd like to have multiple un-saved canvases open at once, and therefore I need a way to easily load one of those canvases into the editor on demand.  Overloading NodeEditorUserCache.LoadNodeCanvas to accept a NodeCanvas pointer seems to be the way to go?

**Comment by richjoslin** [comment]
Didn't notice the SetCanvas method.  I think this does just what I was wanting.

**Comment by Seneral** [comment]
Well the load function doesn't need to be called - it only handles loading from the disk into memory.
When using the NodeEditorUserCache wrapper which manages the canvas you just use the SetCanvas method, true - this essentially does nothing other than assigning the canvas to mainNodeEditor so it's used from then on to draw for example.
