### ISSUE TITLE
Dynamically add or remove knobs in the editor

### ISSUE THREAD

**Issue by molocai** [Seneral/Node_Editor#126]
Hello,

I want to be able to fold/unfold one of my nodes so I need to be able to draw/undraw knobs in the editor. I'm currently doing this in NodeGUI but I cannot remove drawn knobs after I deleted them from the output knobs array.

Any leads?

**Comment by Seneral** [comment]
This is currently not possible​ but is planned for future updates.
One problem with hiding the knobs is the connections of them.
What you could do for now is adding a bool in NodeKnob.cs that toggles visibility in DrawKnob and also change Node.DrawConnections to retarget the connection to the knob's side's center when the knob is set to be invisible;)
Hope this helps, sorry atm I can't help with code very much...
