### ISSUE TITLE
DrawNode

### ISSUE THREAD

**Issue by AtheosCode** [Seneral/Node_Editor#131]
Can we use GUI. Window draw Node to repair the focus the bugs need to click twice。

**Comment by Seneral** [comment]
GUI.window has many limitations and I've come to the conclusion long ago that we're going to be better off making custom windows and handling all controls ourselves.
The focus bug is indeed a problem, but it has other, more convenient workarounds than falling back to the limiting GUI.window.
For example you can disable node reordering (selected nodes popping to the front) which fixes the bug, simply comment the [apropriate line in NodeEditor.DrawSubNodeCanvas](https://github.com/Seneral/Node_Editor/blob/master/Node_Editor/Framework/NodeEditor.cs#L227).
Of course if you want you can add an optional check to fall back to GUI.window and create a pull request:)
